name: Welcome to My Repo

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greeting
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to our repository! 🎉 We're thrilled to have you here. If you have any questions, feel free to ask!"
          pr-message: "Thank you for opening a pull request! 🚀 We appreciate your contribution and look forward to reviewing it."
